// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJZAQfTBgW1RKzN0TOTpG-Y0-ansNy98',
    appId: '1:163385549524:web:c98b61177dfe26c80fd141',
    messagingSenderId: '163385549524',
    projectId: 'flutter-bday-buddy',
    authDomain: 'flutter-bday-buddy.firebaseapp.com',
    storageBucket: 'flutter-bday-buddy.firebasestorage.app',
    measurementId: 'G-64PM5G6XPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARHeSHNniplqknwEK6Li_gWGHeLDWWSmc',
    appId: '1:163385549524:android:8d4b59d41bfae8bf0fd141',
    messagingSenderId: '163385549524',
    projectId: 'flutter-bday-buddy',
    storageBucket: 'flutter-bday-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiGd2xS2a32Wdyz2iVtlhzJdojkDdA0ig',
    appId: '1:163385549524:ios:e06f3c430e2ada170fd141',
    messagingSenderId: '163385549524',
    projectId: 'flutter-bday-buddy',
    storageBucket: 'flutter-bday-buddy.firebasestorage.app',
    iosBundleId: 'com.example.flutterBday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiGd2xS2a32Wdyz2iVtlhzJdojkDdA0ig',
    appId: '1:163385549524:ios:e06f3c430e2ada170fd141',
    messagingSenderId: '163385549524',
    projectId: 'flutter-bday-buddy',
    storageBucket: 'flutter-bday-buddy.firebasestorage.app',
    iosBundleId: 'com.example.flutterBday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMJZAQfTBgW1RKzN0TOTpG-Y0-ansNy98',
    appId: '1:163385549524:web:37e01eb3614dd4630fd141',
    messagingSenderId: '163385549524',
    projectId: 'flutter-bday-buddy',
    authDomain: 'flutter-bday-buddy.firebaseapp.com',
    storageBucket: 'flutter-bday-buddy.firebasestorage.app',
    measurementId: 'G-9EYS4WRR4J',
  );
}
